### ISSUE TITLE
배달취소 배달완료 기능 개발요청

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/iphone-bossapp#28]
[모두사장님_기획안9p.pdf](https://github.com/Taebu/iphone-bossapp/files/3226415/_.9p.pdf)

![image](https://user-images.githubusercontent.com/19964344/58464226-4b3b2b80-8170-11e9-8144-9e88c819a85b.png)

**Comment by Taebu** [comment]
iOS AutoLayout을 활용한 실전 UI구성 전략 - 카카오톡 같은 고급 UI 만들기

팝업 만들기와 애니메이션
popup_1 
16:27
https://www.inflearn.com/course/autolayout-ui_ios/lecture/7344

popup_2 
14:27
https://www.inflearn.com/course/autolayout-ui_ios/lecture/7345

popup_3_animate
4:30
https://www.inflearn.com/course/autolayout-ui_ios/lecture/7346

- 이미 들은 강의지만 쓰지않고 실습은 했는데 생각이 안나 재강의 하면 실제 실습 계획

**Comment by Taebu** [comment]
기능 추가 에 따른 값 추가.

exam_num1| 설명
--|--
3| 배달완료
4 | 배달취소 
 
ordtake에 따른 로그 테이블
insert after
update after 
로그 Trigger작성

**Comment by moonsungjun** [comment]
![menu1_4](https://user-images.githubusercontent.com/19964344/58599039-85641480-82b9-11e9-8c41-70acc5b0753e.png)

**Comment by moonsungjun** [comment]
기존 주문취소 문구를 -> 배달취소 문구로 수정
배달취소 버튼 색상 변경 코드 #b42a23

**Comment by moonsungjun** [comment]
![menu1_4_1](https://user-images.githubusercontent.com/19964344/58599399-1687bb00-82bb-11e9-868d-1d1092dd8a15.png)

**Comment by moonsungjun** [comment]
선택 색상코드 #515152
미 선택 색상코드 #b42a23
뒤로 색상코드 #656565

**Comment by Taebu** [comment]
```sql
CREATE TABLE `ordtake_log` (
  `ot_no` int(11) NOT NULL AUTO_INCREMENT,
  `ot_dml` varchar(255) NOT NULL DEFAULT '' COMMENT 'DML insert, update log',
  `ordtake.seq` int(11) NOT NULL DEFAULT '0' COMMENT 'ordtake seq',
  `ordtake.pay_status` varchar(2) NOT NULL DEFAULT '' COMMENT '주문 상태 변경',
  `ordtake.exam_num1` varchar(2) NOT NULL DEFAULT '' COMMENT '주문 상태 변경',
  `ordtake.exam_num2` varchar(2) NOT NULL DEFAULT '' COMMENT '주문 상태 변경',
  `ot_datetime` datetime NOT NULL DEFAULT '1970-01-01 09:00:00' COMMENT '변경된 시간',
  PRIMARY KEY (`ot_no`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ordtake log 작성 - 20190530'
```

**Comment by Taebu** [comment]
DML Trace
insert trigger
```sql
DROP TRIGGER IF EXISTS `cashq`.`ordtake_AFTER_INSERT`;

DELIMITER $$
USE `cashq`$$
CREATE DEFINER = CURRENT_USER 
TRIGGER `cashq`.`ordtake_AFTER_INSERT` 
AFTER INSERT ON `ordtake` FOR EACH ROW
BEGIN
insert into `ordtake_log` set 
  `ot_dml`='insert',
  `ordtake.seq`=NEW.seq,
  `ordtake.pay_status`=NEW.pay_status,
  `ordtake.exam_num1`=NEW.exam_num1,
  `ordtake.exam_num2`=NEW.exam_num2,
  `ot_datetime`=now();
  
END$$
DELIMITER ;
```

update trigger
```sql
DROP TRIGGER IF EXISTS `cashq`.`ordtake_AFTER_INSERT`;

DELIMITER $$
USE `cashq`$$

CREATE DEFINER=`cashq`@`%` 
TRIGGER `cashq`.`ordtake_AFTER_UPDATE` 
AFTER UPDATE ON `ordtake` FOR EACH ROW
BEGIN
insert into `ordtake_log` set 
  `ot_dml`='update',
  `ordtake.seq`=NEW.seq,
  `ordtake.pay_status`=NEW.pay_status,
  `ordtake.exam_num1`=NEW.exam_num1,
  `ordtake.exam_num2`=NEW.exam_num2,
  `ot_datetime`=now();

END$$
DELIMITER ;
```

**Comment by Taebu** [comment]
![스크린샷 2019-06-13 15 34 43](https://user-images.githubusercontent.com/7663572/59409245-cea38080-8df0-11e9-8855-0c24eb5d55b2.png)
