### ISSUE TITLE
아이폰 -> 메뉴 -> 설정 추가

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/iphone-bossapp#34]
http://cashq.co.kr/adm/sub/smart_menu/menu.php?biz_code=a001&seq=7132
배달 사용여부 ( Y - 사용(기본값) , N - 미사용 ) delivery_yn
![image](https://user-images.githubusercontent.com/19964344/59086884-14b69b00-893e-11e9-9e4f-8ee00a8d727f.png)

![모두사장님_기획안_11-14_페이지_1](https://user-images.githubusercontent.com/19964344/59086736-94903580-893d-11e9-81ef-448094f92b59.png)

http://cashq.co.kr/adm/store_write_dev.php
![image](https://user-images.githubusercontent.com/19964344/59086930-40d21c00-893e-11e9-8334-ff126ad2871e.png)

![모두사장님_기획안_11-14_페이지_2](https://user-images.githubusercontent.com/19964344/59086737-94903580-893d-11e9-8e92-a5826cc5f1f4.png)

http://cashq.co.kr/adm/store_write_dev.php
![image](https://user-images.githubusercontent.com/19964344/59087264-1d5ba100-893f-11e9-8e0b-06e4af6a0c2a.png)

![모두사장님_기획안_11-14_페이지_3](https://user-images.githubusercontent.com/19964344/59086738-94903580-893d-11e9-8b52-a4066dfd07af.png)

http://cashq.co.kr/adm/sub/smart_menu/menu.php?biz_code=a001&seq=7132
![image](https://user-images.githubusercontent.com/19964344/59087297-3c5a3300-893f-11e9-9aed-38b622aea446.png)

![모두사장님_기획안_11-14_페이지_4](https://user-images.githubusercontent.com/19964344/59086739-94903580-893d-11e9-93bc-380cf22c49f5.png)

**Comment by Taebu** [comment]
![스크린샷 2019-06-13 15 29 23](https://user-images.githubusercontent.com/7663572/59408918-0c53d980-8df0-11e9-8814-06bfe5d7d5a4.png)
