### ISSUE TITLE
guide_ios 디자인 수정요청

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/iphone-bossapp#35]
![guide1_ios](https://user-images.githubusercontent.com/19964344/59401856-27feb600-8dd7-11e9-8fbc-2b1202afdcca.png)
![guide2_ios](https://user-images.githubusercontent.com/19964344/59401857-27feb600-8dd7-11e9-99e3-d7bb352eb27b.png)
![guide1_1_ios](https://user-images.githubusercontent.com/19964344/59401858-27feb600-8dd7-11e9-99af-1d2f317c5d11.png)
![guide3_ios](https://user-images.githubusercontent.com/19964344/59401860-27feb600-8dd7-11e9-8bcc-aa729dc4b7b8.png)
![guide4_ios](https://user-images.githubusercontent.com/19964344/59326574-e829c700-8d21-11e9-89b9-3731810d88a9.png)
![guide5_ios](https://user-images.githubusercontent.com/19964344/59326578-e9f38a80-8d21-11e9-9e40-f84a5ff5f91b.png)
[guide_ios.zip](https://github.com/Taebu/iphone-bossapp/files/3279753/guide_ios.zip)

**Comment by Taebu** [comment]
가이드가 다 삼성 배경 가이드 아이폰으로 변경 바람.

**Comment by Taebu** [comment]
적용완료
