### ISSUE TITLE
메뉴 ui 디자인 변경

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/iphone-bossapp#36]
![제목-없음-2](https://user-images.githubusercontent.com/19964344/59327573-deee2980-8d24-11e9-931f-c919a1b3c430.png)

**Comment by Taebu** [comment]
![스크린샷 2019-06-13 15 28 20](https://user-images.githubusercontent.com/7663572/59408874-e75f6680-8def-11e9-80af-c642fb97d279.png)
