### ISSUE TITLE
출시 임박 음성 데이터 크몽에 접수

### ISSUE THREAD

**Issue by Taebu** [Taebu/iphone-bossapp#37]
모두사장님 주문!
모두톡 주문!
주문이 들어왔어요!
사장님! 주문!
톡톡! 주문!
딩동댕! 사장님 주문!
띵동! 사장님 주문!
사장님! 주문! 주문!
사장님! 주문 들어왔어요!
사장님! 주문yo! 주문yo!
사장님! 또또또또! 주문왔네또!
주문이 접수 되었습니다.
주문이 취소 되었습니다.
결제가 취소 되었습니다.
주문이 자동취소 되었습니다.
주문포인트가 지급되었습니다!

**Comment by moonsungjun** [comment]
[모두사장님 주문_멘트의뢰.docx](https://github.com/Taebu/iphone-bossapp/files/3288860/_.docx)

**Comment by moonsungjun** [comment]
1.wav모두사장님 주문!
2.wav 모두톡 주문!
3.wav 주문이 들어왔어요!
4.wav 사장님! 주문!
5.wav 톡톡! 주문!
6.wav 딩동댕! 사장님 주문!
7.wav 띵동! 사장님 주문!
8.wav 사장님! 주문! 주문!
9.wav 사장님! 주문 들어왔어요!
10.wav 사장님! 주문yo! 주문yo!
11.wav 사장님! 또또또또! 주문왔네! 또! 주문!
12.wav 주문이 접수 되었습니다.
13.wav 주문이 취소 되었습니다.
14.wav 결제가 취소 되었습니다.
15.wav 주문이 자동취소 되었습니다.
주문포인트가 지급되었습니다!

**Comment by moonsungjun** [comment]
[모두사장님.zip](https://github.com/Taebu/iphone-bossapp/files/3294759/default.zip)

**Comment by moonsungjun** [comment]
주문접수 알림멘트는 7.wav파일 적용 요청.
※나머지 멘트에 대해서는 추후 회의 통하여 결정.

**Comment by moonsungjun** [comment]
[7.zip](https://github.com/Taebu/iphone-bossapp/files/3294818/7.zip)
7.wav 8초 멘트

**Comment by moonsungjun** [comment]
9.wav 파일 선택
[9.zip](https://github.com/Taebu/iphone-bossapp/files/3299876/9.zip)
